//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyJSL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public long Código_de_facturas { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<long> Código { get; set; }
        public Nullable<long> idProducto { get; set; }
        public Nullable<int> Numerodepago { get; set; }
    }
}
